### ISSUE TITLE
Readhub 域名变更通知

### ISSUE THREAD

**Issue by NoNameNoBuilding** [roger-yh99/Readhub#1]
你好，我是无码科技的工作人员，目前在无码科技负责 Readhub 内容运营。

谢谢你为我们开发了 Readhub for JetBrains 客户端。有一个服务上的变动需要跟你同步下，Readhub 网站的域名由之前的 https://readhub.me 变更为 https://readhub.cn ，如果你这边方便的话，可以同步更新下。辛苦了，多谢。

如有任何疑问或建议，可随时与我联系，我的联系方式：mazhai@nocode.com。

最后，再次感谢你对我们的支持。祝好。

**Comment by yaohui-wyh** [comment]
Fixed in v1.0.2
