### ISSUE TITLE
Would you like to consider migration to kohttp dsl for requests?

### ISSUE THREAD

**Issue by rybalkinsd** [roger-yh99/Readhub#5]
https://github.com/alex-yh99/Readhub/blob/2b225e830245d34327cbf80a2c9c8a9ac523cafb/src/com/madfish/ide/util/RHApi.kt#L69

kohttp team could help with it :)

**Comment by yaohui-wyh** [comment]
Thanks Sergey @rybalkinsd 
This plugin is not actively maintained, I will try kohttp in other projects :)
