### ISSUE TITLE
无法获取信息内容

### ISSUE THREAD

**Issue by floatval** [roger-yh99/Readhub#6]
# 网络环境
内网，有透明代理

# 表现情况
IDE 里的需要网络的功能，在设置过代理之后，可以正常使用。
但是 Readhub 插件无法正常使用。

**Comment by yaohui-wyh** [comment]
@floatval 已经修复，Proxy 配置之后需重启生效
可手动下载新 zip 包更新（[GitHub Release](https://github.com/yaohui-wyh/Readhub/releases/download/v1.1.1/Readhub-1.1.1.zip)），或待 JetBrains Plugin 插件更新后（[地址](https://plugins.jetbrains.com/plugin/10539-readhub)）基于升级提示更新就好了
